from django.core.management.base import BaseCommand
from api.models import EvolutionTrigger

DEFAULT_EVO_TRIGGERS = [
    ('Level','Level Up','Level'),
    ('LevelMale','Level Up if Male','Level'),
    ('LevelFemale','Level Up if Female','Level'),
    ('LevelDay','Level Up during daytime','Level'),
    ('LevelNight','Level Up during night','Level'),
    ('LevelMorning','Level Up in the morning','Level'),
    ('LevelAfternoon','Level Up in the afternoon','Level'),
    ('LevelEvening','Level Up in the evening','Level'),
    ('LevelNoWeather','Level Up in clear weather','Level'),
    ('LevelSun','Level Up in strong sunlight','Level'),
    ('LevelRain','Level Up in rain','Level'),
    ('LevelSnow','Level Up in snow','Level'),
    ('LevelSandstorm','Level Up in sandtorm','Level'),
    ('LevelCycling','Level Up while cycling','Level'),
    ('LevelSurfing','Level Up while surfing','Level'),
    ('LevelDiving','Level Up while diving','Level'),
    ('LevelDarkness','Level Up in dark area','Level'),
    ('LevelDarkInParty','Level Up if there is a Dark-type Pokemon in party','Level'),
    ('AttackGreater','Level Up with Attack greater than Defense','Level'),
    ('DefenseGreater','Level Up with Defense greater than Attack','Level'),
    ('AtkDefEqual','Level Up with Attack and Defense equal','Level'),
    ('LevelRandom','Level Up into one of the evolution branches randomly with equal chance','Level'),
    ('Shed','Level Up and the Shedded skin transforms into a Pokemon','Level'),
    ('Happiness','Level Up with high friendship',''),
    ('HappinessMale','Level Up with high friendship if Male',''),
    ('HappinessFemale','Level Up with high friendship if Female',''),
    ('HappinessDay','Level Up with high friendship during daytime',''),
    ('HappinessNight','Level Up with high friendship during night',''),
    ('HappinessMove','Level Up with high friendship knowing a ceftain move','Move'),
    ('HappinessMoveType','Level Up with high friendship knowing any move of certain type','Type'),
    ('HappinessHoldItem','Level Up with high friendship and holding a certain item','Item'),
    ('MaxHappiness','Level Up with maximum friendship',''),
    ('Beauty','Level Up with high beauty stat','Beauty'),
    ('HoldItem','Level Up while holding item','Item'),
    ('HoldItemMale','Level Up while holding item if Male','Item'),
    ('HoldItemFemale','Level Up while holding item if Female','Item'),
    ('HoldItemDay','Level Up while holding item during daytime','Item'),
    ('HoldItemNight','Level Up while holding item during night','Item'),
    ('HasMove','Level Up while knowing certain move','Move'),
    ('HasMoveType','Level Up while knowing any move of certain type','Type'),
    ('HasInParty','Level Up while having a certain species in party','Species'),
    ('Location','Level Up in a certain location','Location'),
    ('Item','Use certain item','Item'),
    ('ItemMale','Use certain item if Male','Item'),
    ('ItemFeMale','Use certain item if Female','Item'),
    ('ItemDay','Use certain item during daytime','Item'),
    ('ItemNight','Use certain item during night','Item'),
    ('ItemHappiness','Use certain item with igh friendship','Item'),
    ('Trade','Trade',''),
    ('TradeMale','Trade if Male',''),
    ('TradeFemale','Trade if Female',''),
    ('TradeDay','Trade during daytime',''),
    ('TradeNight','Trade during night',''),
    ('TradeHoldItem','Trade holding item','Item'),
    ('TradeSpecies','Trade for a particular Species','Species'),
    ('BattleDealCriticalHit','Deal certain number of critical hits','Number'),
    ('AfterDamageTaken','Take certain damage','Number'),



]

